import { createDefaultPlan } from "./defaults.ts";
import type { IncomeStream, Plan } from "./types.ts";

/** True when Observe or Orient already has something a demo would erase. */
export function planHasEntries(plan: Plan): boolean {
  if (plan.primary.name.trim() || plan.primary.birthDate.trim()) return true;
  if (plan.spouse.name.trim() || plan.spouse.birthDate.trim()) return true;
  if (plan.children.length > 0) return true;
  if (plan.portfolios.length > 0) return true;
  if ((plan.liabilities ?? []).length > 0) return true;
  if (plan.incomes.length > 0) return true;
  if (plan.spending.length > 0) return true;
  if (plan.contributions.length > 0) return true;
  return false;
}

function wage(
  id: string,
  name: string,
  kind: IncomeStream["kind"],
  monthlyAmount: number,
  startDate: string,
  endDate: string | null,
  person: IncomeStream["person"],
  taxTreatment: IncomeStream["taxTreatment"] = "ordinary",
): IncomeStream {
  return {
    id,
    name,
    kind,
    monthlyAmount,
    startDate,
    endDate,
    colaPct: null,
    taxTreatment,
    person,
  };
}

/**
 * Diligent couple in their late 30s / early 40s.
 * Earned pay runs about 35 years and stops at retirement.
 * Pension and Social Security start after that. They do not work to age 95.
 * Spending does not include the mortgage or the car payment.
 */
export function demoPlan(): Plan {
  const base = createDefaultPlan();
  return {
    ...base,
    primary: { name: "Jordan Hale", birthDate: "1986-04-12" },
    spouse: { name: "Riley Hale", birthDate: "1991-04-12" },
    children: [
      { id: "demo-sam", name: "Sam Hale", birthDate: "2016-05-14" },
      { id: "demo-quinn", name: "Quinn Hale", birthDate: "2018-11-02" },
      { id: "demo-avery", name: "Avery Hale", birthDate: "2021-07-19" },
    ],
    assumptions: {
      ...base.assumptions,
      asOfDate: "2026-10-01",
      asOfPinned: true,
      inflationPct: 2.5,
      defaultColaPct: 2.5,
      defaultReturnPct: 7,
      retirementGoalDate: "2051-04-01",
      nestEggGoal: 2_500_000,
      sweepPortfolioId: "demo-savings",
    },
    portfolios: [
      {
        id: "demo-checking",
        name: "Checking",
        kind: "cash",
        owner: "joint",
        currentValue: 12_500,
        returnPct: null,
        taxBucket: "none",
        spendable: true,
        includeInNetWorth: true,
        institutionId: null,
        institutionName: "",
      },
      {
        id: "demo-savings",
        name: "Savings",
        kind: "cash",
        owner: "joint",
        currentValue: 36_000,
        returnPct: null,
        taxBucket: "none",
        spendable: true,
        includeInNetWorth: true,
        institutionId: null,
        institutionName: "",
      },
      {
        id: "demo-401k",
        name: "Jordan 401(k)",
        kind: "401k",
        owner: "primary",
        currentValue: 385_000,
        returnPct: null,
        taxBucket: "pre_tax",
        spendable: true,
        includeInNetWorth: true,
        institutionId: null,
        institutionName: "",
      },
      {
        id: "demo-riley-401k",
        name: "Riley 401(k)",
        kind: "401k",
        owner: "spouse",
        currentValue: 210_000,
        returnPct: null,
        taxBucket: "pre_tax",
        spendable: true,
        includeInNetWorth: true,
        institutionId: null,
        institutionName: "",
      },
      {
        id: "demo-roth",
        name: "Riley Roth IRA",
        kind: "roth_ira",
        owner: "spouse",
        currentValue: 62_000,
        returnPct: null,
        taxBucket: "roth",
        spendable: true,
        includeInNetWorth: true,
        institutionId: null,
        institutionName: "",
      },
      {
        id: "demo-brokerage",
        name: "Brokerage",
        kind: "taxable",
        owner: "joint",
        currentValue: 72_000,
        returnPct: null,
        taxBucket: "taxable",
        spendable: true,
        includeInNetWorth: true,
        institutionId: null,
        institutionName: "",
      },
      {
        id: "demo-home",
        name: "Home",
        kind: "real_estate",
        owner: "joint",
        currentValue: 685_000,
        returnPct: null,
        taxBucket: "none",
        spendable: false,
        includeInNetWorth: true,
        institutionId: null,
        institutionName: "",
        mortgage: {
          originationDate: "2018-06-01",
          aprPct: 3.5,
          monthlyPi: 2140,
          termYears: 30,
          includeInSpending: true,
          associated: true,
          institutionId: null,
          institutionName: "",
        },
      },
    ],
    liabilities: [
      {
        id: "demo-car",
        name: "Car loan",
        kind: "car",
        balance: 18_000,
        aprPct: 5.9,
        monthlyPi: 465,
        originationDate: "2024-08-01",
        termYears: 5,
        includeInSpending: true,
        owner: "joint",
        institutionId: null,
        institutionName: "",
      },
    ],
    incomes: [
      wage(
        "demo-jordan-pay",
        "Jordan salary",
        "salary",
        10_400,
        "2016-04-01",
        "2051-03-01",
        "primary",
      ),
      wage(
        "demo-riley-pay",
        "Riley salary",
        "salary",
        7_600,
        "2016-10-01",
        "2051-03-01",
        "spouse",
      ),
      wage(
        "demo-jordan-bonus",
        "Jordan bonus",
        "bonus",
        1_100,
        "2019-01-01",
        "2051-03-01",
        "primary",
      ),
      wage(
        "demo-riley-other",
        "Riley side income",
        "other",
        650,
        "2024-01-01",
        "2042-12-01",
        "spouse",
      ),
      wage(
        "demo-jordan-pension",
        "Jordan pension",
        "pension",
        3_200,
        "2051-04-01",
        null,
        "primary",
      ),
      wage(
        "demo-riley-pension",
        "Riley pension",
        "pension",
        1_800,
        "2051-04-01",
        null,
        "spouse",
      ),
      {
        id: "demo-jordan-ss",
        name: "Jordan Social Security",
        kind: "ss",
        monthlyAmount: 3_050,
        startDate: "2053-04-12",
        endDate: "2081-04-12",
        colaPct: null,
        taxTreatment: "ss",
        person: "primary",
        ssPia: 3_050,
        ssClaimAge: 67,
        ssFra: 67,
        ssEstimated: false,
      },
      {
        id: "demo-riley-ss",
        name: "Riley Social Security",
        kind: "ss",
        monthlyAmount: 2_150,
        startDate: "2058-04-12",
        endDate: "2086-04-12",
        colaPct: null,
        taxTreatment: "ss",
        person: "spouse",
        ssPia: 2_150,
        ssClaimAge: 67,
        ssFra: 67,
        ssEstimated: false,
      },
    ],
    spending: [
      {
        id: "demo-spend",
        label: "Household",
        monthlyAmount: 7_800,
        startDate: "2026-10-01",
        endDate: null,
      },
    ],
    contributions: [
      {
        id: "demo-401k-contrib",
        label: "Jordan 401(k)",
        portfolioId: "demo-401k",
        monthlyAmount: 1_500,
        startDate: "2026-10-01",
        endDate: "2050-12-01",
        amountMode: "fixed",
        percentOfIncome: null,
        percentOfIncomeId: null,
        employerMatch: true,
        employerMatchPct: 50,
        capToIrsLimit: false,
        capPerson: "primary",
        endAtRetirement: false,
      },
      {
        id: "demo-riley-401k-contrib",
        label: "Riley 401(k)",
        portfolioId: "demo-riley-401k",
        monthlyAmount: 800,
        startDate: "2026-10-01",
        endDate: "2050-12-01",
        amountMode: "fixed",
        percentOfIncome: null,
        percentOfIncomeId: null,
        employerMatch: true,
        employerMatchPct: 50,
        capToIrsLimit: false,
        capPerson: "spouse",
        endAtRetirement: false,
      },
      {
        id: "demo-roth-contrib",
        label: "Riley Roth IRA",
        portfolioId: "demo-roth",
        monthlyAmount: 500,
        startDate: "2026-10-01",
        endDate: "2050-12-01",
        amountMode: "fixed",
        percentOfIncome: null,
        percentOfIncomeId: null,
        employerMatch: false,
        employerMatchPct: 0,
        capToIrsLimit: false,
        capPerson: "spouse",
        endAtRetirement: false,
      },
      {
        id: "demo-brokerage-contrib",
        label: "Brokerage",
        portfolioId: "demo-brokerage",
        monthlyAmount: 400,
        startDate: "2026-10-01",
        endDate: "2050-12-01",
        amountMode: "fixed",
        percentOfIncome: null,
        percentOfIncomeId: null,
        employerMatch: false,
        employerMatchPct: 0,
        capToIrsLimit: false,
        endAtRetirement: false,
      },
    ],
    confirmations: [],
  };
}
